apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" .}}-license
  labels:
    name: gw-license
  annotations:
    description: Template for Secrets for the Gateway license
type: Opaque
data:
  license: {{ .Values.gateway.license.value | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: gw-pm-credentials
  labels:
    name: gw-pm-credentials
  annotations:
    description: Template for Credentials for the Gateway Policy Manager
type: Opaque
data:
  ssg-admin-username: {{ .Values.gateway.adminUsername | b64enc | quote }}
  {{- if .Values.gateway.adminPassword }}
  ssg-admin-password: {{ .Values.gateway.adminPassword | b64enc | quote }}
  {{ else }}
  ssg-admin-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
